# Autogenerated wrapper script for p3a_jll for x86_64-unknown-freebsd
export libp3a

using Kokkos_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("p3a")
JLLWrappers.@declare_library_product(libp3a, "libp3a.so")
function __init__()
    JLLWrappers.@generate_init_header(Kokkos_jll, MPICH_jll)
    JLLWrappers.@init_library_product(
        libp3a,
        "lib/libp3a.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
